# Generated by Django 4.1.3 on 2022-12-06 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_brand'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
