# Generated by Django 4.1.3 on 2022-12-06 20:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_remove_variation_product_delete_product_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
