# Generated by Django 4.1.3 on 2022-12-06 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_brand_color_product_size_productattribute'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productattribute',
            name='colors',
        ),
        migrations.RemoveField(
            model_name='productattribute',
            name='sizes',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='store.product'),
        ),
        migrations.AddField(
            model_name='productattribute',
            name='sizes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_sizes', to='store.size'),
        ),
    ]
