# Generated by Django 4.1.3 on 2022-12-08 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_remove_productattribute_colors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productattribute',
            name='colors',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_colors', to='store.color'),
        ),
    ]
