# Generated by Django 4.1.3 on 2022-12-08 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_gender_alter_productattribute_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='gender',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
