# Generated by Django 4.1.3 on 2022-12-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0023_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.AddField(
            model_name='productattribute',
            name='quantinty',
            field=models.IntegerField(default=0),
        ),
    ]
