# Generated by Django 4.1.3 on 2022-12-09 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0024_remove_product_stock_productattribute_quantinty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='brand_image',
            field=models.ImageField(null=True, upload_to='photos/brand'),
        ),
    ]
