# Generated by Django 4.1.3 on 2022-12-10 04:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0027_alter_productattribute_colors_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='variant',
        ),
    ]
