# Generated by Django 4.1.3 on 2022-12-25 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_variation_remove_productattribute_colors_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_image',
            new_name='image',
        ),
    ]
