# Generated by Django 4.1.3 on 2022-12-25 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0030_rename_brand_image_brand_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='brand_description',
        ),
    ]
