# Generated by Django 4.1.3 on 2023-01-06 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0032_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_percetage',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(default=0),
        ),
    ]
