# Generated by Django 4.1.3 on 2023-01-06 12:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0033_product_offer_percetage_alter_product_original_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='offer_percetage',
        ),
        migrations.AlterField(
            model_name='product',
            name='original_price',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
