# Generated by Django 4.1.3 on 2023-01-08 12:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0034_remove_product_offer_percetage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_percentage',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(70)]),
        ),
    ]
