# Generated by Django 4.1.3 on 2023-01-08 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0035_product_offer_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_trendingv',
            field=models.BooleanField(default=False),
        ),
    ]
