# Generated by Django 4.1.3 on 2023-01-08 17:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0036_product_is_trendingv'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='is_trendingv',
            new_name='is_trending',
        ),
    ]
