# Generated by Django 4.1.3 on 2022-12-22 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_alter_userprofile_user_address'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='zipcode',
            new_name='pincode',
        ),
    ]
