# Generated by Django 4.1.3 on 2022-12-26 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_address_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='signup_day',
            field=models.CharField(default=26, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='signup_month',
            field=models.CharField(default=12, max_length=50),
        ),
        migrations.AddField(
            model_name='account',
            name='signup_year',
            field=models.CharField(default=2022, max_length=50),
        ),
    ]
