# Generated by Django 4.1.3 on 2022-12-27 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_account_signup_day_account_signup_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='signup_day',
            field=models.CharField(default=27, max_length=50),
        ),
    ]
