# Generated by Django 4.1.3 on 2022-12-30 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_alter_account_signup_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='signup_day',
            field=models.CharField(default=30, max_length=50),
        ),
    ]
