# Generated by Django 4.1.3 on 2023-01-01 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_alter_account_signup_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='signup_day',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='signup_month',
            field=models.CharField(default=1, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='signup_year',
            field=models.CharField(default=2023, max_length=50),
        ),
    ]
