# Generated by Django 4.1.3 on 2023-01-02 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_alter_account_signup_day_return_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='return_request',
            name='order_number',
            field=models.CharField(default=1, max_length=15),
        ),
    ]
