# Generated by Django 4.1.3 on 2023-01-08 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_alter_account_signup_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='signup_day',
            field=models.CharField(default=8, max_length=50),
        ),
    ]
