# Generated by Django 4.1.3 on 2022-12-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0029_variation_remove_productattribute_colors_and_more'),
        ('cart', '0002_alter_cartitem_variations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='variations',
            field=models.ManyToManyField(blank=True, to='store.variation'),
        ),
    ]
