# Generated by Django 4.1.3 on 2022-12-14 09:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pincode',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinLengthValidator(6)]),
        ),
    ]
