# Generated by Django 4.1.3 on 2022-12-19 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='order_number',
            field=models.CharField(default=1, max_length=20),
        ),
    ]
