# Generated by Django 4.1.3 on 2022-12-22 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproduct',
            name='is_ordered',
            field=models.BooleanField(default=False),
        ),
    ]
