# Generated by Django 4.1.3 on 2022-12-23 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orders_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='phone',
        ),
    ]
