# Generated by Django 4.1.3 on 2022-12-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_remove_orders_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_id',
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_id',
            field=models.CharField(default=0, max_length=250),
        ),
        migrations.AddField(
            model_name='orders',
            name='payment_mode',
            field=models.CharField(default=0, max_length=150),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=10),
        ),
        migrations.AlterField(
            model_name='orders',
            name='status',
            field=models.CharField(choices=[('Placed', 'Placed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='Placed', max_length=10),
        ),
    ]
