# Generated by Django 4.1.3 on 2022-12-26 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0012_orderproducts'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderproducts',
            name='Order_day',
            field=models.IntegerField(default=26),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='Order_month',
            field=models.IntegerField(default=12),
        ),
        migrations.AddField(
            model_name='orderproducts',
            name='Order_year',
            field=models.IntegerField(default=2022),
        ),
    ]
