# Generated by Django 4.1.3 on 2023-01-02 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_alter_orders_order_day_alter_orders_order_month_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orders',
            name='Order_day',
            field=models.IntegerField(default=2),
        ),
    ]
